config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-deploy:
      branch: master
      repo: https://github.com/EOSC-synergy/saps-deploy
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-deploy git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-charcoal-caiman.sh
        container: qc.acc_hazy-amethyst-bombay
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-deploy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-charcoal-peccary.sh
        container: qc.doc_smelly-flax-rattlesnake
      github.com/EOSC-synergy/saps-deploy git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-coral-macaw.sh
        container: qc.doc_muggy-aqua-hummingbird
      github.com/EOSC-synergy/saps-deploy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-magnolia-labradoodle.sh
        container: qc.doc_messy-auburn-gecko
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-deploy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-celadon-frog.sh
        container: qc.lic_scanty-ivory-dhole
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-deploy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-salmon-ostrich.sh
        container: qc.sec_whiny-periwinkle-shrew
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-deploy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-green-antelope.sh
        container: qc.sty_gloppy-lime-tamarin
      github.com/EOSC-synergy/saps-deploy jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-lemon-bombay.sh
        container: qc.sty_lovely-alizarin-robin
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-deploy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-violet-mongrel.sh
        container: qc.ver_shaggy-salmon-tiger
timeout: 5400
